version: '3'

services:
    web-nginx:
        image: nginx:stable-alpine
        container_name: web-nginx
        volumes:
            - "./docker-web/www:/usr/share/nginx/html:ro"
            - "./docker-web/log:/var/log/nginx"
            - "./docker-web/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"

    web-php:
        build: ./docker-web/.build-php
        container_name: web-php
        volumes:
            - "./docker-web/www:/script:ro"

    web-mysql:
        image: hypriot/rpi-mysql
        container_name: web-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: heyputyourpasswordhereiwillnotgiveyoumine
    adminer:
      image: adminer
      restart: always
      ports:
          - 8888:8080
      environment:
        ADMINER_DEFAULT_SERVER: web-mysql
